### ISSUE TITLE
self-host

### ISSUE THREAD

**Issue by Benroyz** [Arham4/RuneBot#20]
Hi!  I am having a problem, I've installed what it seems to be required(postgresql), and I tried to run the bot. 

I am self-hosting the bot with just a few of my friends. 

There is the issue:
`RuneBot.kt: line 1: package: command not found
RuneBot.kt: line 3: import: command not found
RuneBot.kt: line 4: import: command not found
RuneBot.kt: line 5: import: command not found
RuneBot.kt: line 6: import: command not found
RuneBot.kt: line 7: import: command not found
RuneBot.kt: line 8: import: command not found
RuneBot.kt: line 9: import: command not found
RuneBot.kt: line 10: import: command not found
RuneBot.kt: line 11: import: command not found
RuneBot.kt: line 12: import: command not found
RuneBot.kt: line 13: import: command not found
RuneBot.kt: line 14: import: command not found
RuneBot.kt: line 15: import: command not found
RuneBot.kt: line 16: import: command not found
RuneBot.kt: line 17: import: command not found
RuneBot.kt: line 19: /bin: Is a directory
RuneBot.kt: line 20: commands: command not found
RuneBot.kt: line 21: commands/: Is a directory
RuneBot.kt: line 22: object: command not found
RuneBot.kt: line 24: @JvmStatic: command not found
RuneBot.kt: line 25: syntax error near unexpected token `('
RuneBot.kt: line 25: `    fun main(args: Array<String>) {'
`

What do I need to do with this? Will you show some support with this? I am running Linux Ubuntu 12.04.

**Comment by Arham4** [comment]
It doesn't seem like you have Kotlin configured on your computer!

**Comment by Benroyz** [comment]
I managed to get it installed.  However, I am running it through Linux VPS.  Now I'm having issues. I don't know how to run it through maven, so could you lead me to learn how to run it?

**Comment by Arham4** [comment]
Instructions on installing Maven can be found [on the Maven website](https://maven.apache.org/install.html), which will probably explain it way better than I can. After that, to run the project, use the command `mvn clean install` in your terminal at the directory of the bot.

**Comment by Benroyz** [comment]
Ok, so, I did ``mvn clean install`` and I got the result back when I tried to install: 

> no main manifest attribute, in RuneBot-1.0-SNAPSHOT.jar

I attempted to try src folder from the bot directory, which the build worked. The startup did not work, though

**Comment by Benroyz** [comment]
Ok, so I added the table according to README, and have database setup properly in config.yml and pom.xml -- Yet I got this issue: https://pastebin.com/zgy0r6DV

**Comment by Arham4** [comment]
Hey, I'll be looking into this myself trying to make it work from Terminal. Meanwhile, your best shot may be running from your IDE on your local computer. So sorry about that, the bot is still very new and in development stages still. Thank you.

**Comment by Benroyz** [comment]
Alright. Let me know when you finally get this working through terminal, so I'll wait and check from now and then.  Thanks!

**Comment by Arham4** [comment]
I ran the `mvn clean install` command and received the following: https://pastebin.com/mAB2UsnW

Maybe a solution would be to attempt to run the bot from your actual computer, then transferring all of those files to your VPS. The reason I say this is because perhaps when it properly runs from IntelliJ, all the needed files and such may be created to make it successful when running it from Terminal.

I say this due to your previous error: 

> no main manifest attribute, in RuneBot-1.0-SNAPSHOT.jar

My target folder looks like this: https://dl.dropboxusercontent.com/s/gsh56yvhs6yah7b/target.rar
Try to first properly run the bot from your local computer before attempting to run from the Terminal on your VPS. Be assured the credentials are right in `config.yaml` to assure `jooq` makes the needed classes to work.

**Comment by Benroyz** [comment]
Before I do this stuff, are you using Windows?  I've mentioned that I am using Linuix through terminal.  Transferring the files over to the VPS will end up being a little bit more confusing, possibly messy.

**Comment by Arham4** [comment]
Yeah, I am using Windows, but I don't see why what I suggested would be different system to system. Do correct me if I'm wrong. I'm kind of puzzled by your issue since I just tried making a new folder with a fresh clone of the repo, doing `mvn clean install`, and it results in a successful build.

**Comment by Arham4** [comment]
Hey! I started working with my command line more and figured out recently how to run the program using maven (though this is assuming build is correct). The command is the following:
```mvn exec:java -Dexec.mainClass="com.gmail.arhamjsiddiqui.runebot.RuneBot"```

**Comment by Benroyz** [comment]
`[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for                                                 groupId:RuneBot:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-comp                                                iler-plugin is missing. @ line 101, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten t                                                he stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support buildin                                                g such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building RuneBot 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ RuneBot ---
[INFO]
[INFO] --- jooq-codegen-maven:3.10.4:generate (default) @ RuneBot ---
[INFO] No <inputCatalog/> was provided. Generating ALL available catalogs instea                                                d.
[INFO] License parameters
[INFO] ----------------------------------------------------------
[INFO]   Thank you for using jOOQ and jOOQ's code generator
[INFO]
[INFO] Database parameters
[INFO] ----------------------------------------------------------
[INFO]   dialect                : POSTGRES
[INFO]   URL                    : jdbc:postgresql://localhost:5432/RuneBot02
[INFO]   target dir             : /root/RuneBot/RuneBot/target/generated-sources                                                /jooq
[INFO]   target package         : com.gmail.arhamjsiddiqui.runebot.jooq
[INFO]   includes               : [.*]
[INFO]   excludes               : []
[INFO]   includeExcludeColumns  : false
[INFO] ----------------------------------------------------------
[INFO]
[INFO] JavaGenerator parameters
[INFO] ----------------------------------------------------------
[INFO]   strategy               : class org.jooq.util.DefaultGeneratorStrategy
[INFO]   deprecated             : true
[INFO]   generated annotation   : true
[INFO]   JPA annotations        : false
[INFO]   validation annotations : false
[INFO]   instance fields        : true
[INFO]   sequences              : true
[INFO]   udts                   : true
[INFO]   routines               : true
[INFO]   tables                 : true
[INFO]   records                : true
[INFO]   pojos                  : false
[INFO]   immutable pojos        : false
[INFO]   interfaces             : false
[INFO]   immutable interfaces   : false
[INFO]   daos                   : false
[INFO]   indexes                : true
[INFO]   relations              : true
[INFO]   table-valued functions : true
[INFO]   global references      : true
[INFO] ----------------------------------------------------------
[INFO]
[INFO] Generation remarks
[INFO] ----------------------------------------------------------
[INFO]
[INFO] ----------------------------------------------------------
[INFO] Generating catalogs      : Total: 1
[INFO]

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.10.4

[INFO] ARRAYs fetched           : 0 (0 included, 0 excluded)
[INFO] Enums fetched            : 0 (0 included, 0 excluded)
[INFO] Packages fetched         : 0 (0 included, 0 excluded)
[INFO] Routines fetched         : 0 (0 included, 0 excluded)
[INFO] Tables fetched           : 0 (0 included, 0 excluded)
[INFO] UDTs fetched             : 0 (0 included, 0 excluded)
[INFO] Excluding empty catalog  :
[INFO] Removing excess files
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ RuneBot --                                                -
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i                                                .e. build is platform dependent!
[INFO] skip non existing resourceDirectory /root/RuneBot/RuneBot/src/main/resour                                                ces
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ RuneBot ---
[INFO] No sources to compile
[INFO]
[INFO] --- kotlin-maven-plugin:1.2.10:compile (compile) @ RuneBot ---
[WARNING] Runtime JAR files in the classpath should have the same version. These                                                 files were found in the classpath:
    /root/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.2.10/kotlin-s                                                tdlib-jdk8-1.2.10.jar (version 1.2)
    /root/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.2.10/kotlin-stdlib                                                -1.2.10.jar (version 1.2)
    /root/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.2.10/kotlin-s                                                tdlib-jdk7-1.2.10.jar (version 1.2)
    /root/.m2/repository/org/jetbrains/kotlin/kotlin-reflect/1.1.3/kotlin-reflec                                                t-1.1.3.jar (version 1.1)
[WARNING] Consider providing an explicit dependency on kotlin-reflect 1.2 to pre                                                vent strange errors
[WARNING] Some runtime JAR files in the classpath have an incompatible version.                                                 Consider removing them from the classpath or use '-Xskip-runtime-version-check'                                                 to suppress this warning
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/R                                                uneBot.kt: (7, 41) Unresolved reference: jooq
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/R                                                uneBot.kt: (30, 71) Unresolved reference: Players
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/R                                                uneBot.kt: (30, 88) Cannot choose among the following candidates without complet                                                ing type inference:
@HidesMembers public inline fun <T> Iterable<???>.forEach(action: (???) -> Unit)                                                : Unit defined in kotlin.collections
@HidesMembers public inline fun <K, V> Map<out ???, ???>.forEach(action: (Map.En                                                try<???, ???>) -> Unit): Unit defined in kotlin.collections
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/R                                                uneBot.kt: (30, 98) Cannot infer a type for this parameter. Please specify it ex                                                plicitly.
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt: (12, 41) Unresolved reference: jooq
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt: (13, 41) Unresolved reference: jooq
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt: (45, 49) Unresolved reference: PlayersRecord
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt: (50, 45) Cannot infer a type for this parameter. Please specify                                                 it explicitly.
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt: (50, 52) Cannot infer a type for this parameter. Please specify                                                 it explicitly.
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt: (110, 53) Unresolved reference: Players
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt: (111, 78) Unresolved reference: Players
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt: (118, 51) Unresolved reference: Players
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt: (118, 70) Cannot choose among the following candidates without                                                 completing type inference:
@HidesMembers public inline fun <T> Iterable<???>.forEach(action: (???) -> Unit)                                                : Unit defined in kotlin.collections
@HidesMembers public inline fun <K, V> Map<out ???, ???>.forEach(action: (Map.En                                                try<???, ???>) -> Unit): Unit defined in kotlin.collections
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt: (118, 80) Cannot infer a type for this parameter. Please specif                                                y it explicitly.
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt: (129, 62) Unresolved reference: PlayersRecord
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.534 s
[INFO] Finished at: 2018-04-20T18:15:00-04:00
[INFO] Final Memory: 34M/110M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.2.10:c                                                ompile (compile) on project RuneBot: Compilation failure: Compilation failure:
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/R                                                uneBot.kt:[7,41] Unresolved reference: jooq
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/R                                                uneBot.kt:[30,71] Unresolved reference: Players
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/R                                                uneBot.kt:[30,88] Cannot choose among the following candidates without completin                                                g type inference:
[ERROR] @HidesMembers public inline fun <T> Iterable<???>.forEach(action: (???)                                                 -> Unit): Unit defined in kotlin.collections
[ERROR] @HidesMembers public inline fun <K, V> Map<out ???, ???>.forEach(action:                                                 (Map.Entry<???, ???>) -> Unit): Unit defined in kotlin.collections
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/R                                                uneBot.kt:[30,98] Cannot infer a type for this parameter. Please specify it expl                                                icitly.
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt:[12,41] Unresolved reference: jooq
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt:[13,41] Unresolved reference: jooq
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt:[45,49] Unresolved reference: PlayersRecord
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt:[50,45] Cannot infer a type for this parameter. Please specify i                                                t explicitly.
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt:[50,52] Cannot infer a type for this parameter. Please specify i                                                t explicitly.
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt:[110,53] Unresolved reference: Players
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt:[111,78] Unresolved reference: Players
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt:[118,51] Unresolved reference: Players
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt:[118,70] Cannot choose among the following candidates without co                                                mpleting type inference:
[ERROR] @HidesMembers public inline fun <T> Iterable<???>.forEach(action: (???)                                                 -> Unit): Unit defined in kotlin.collections
[ERROR] @HidesMembers public inline fun <K, V> Map<out ???, ???>.forEach(action:                                                 (Map.Entry<???, ???>) -> Unit): Unit defined in kotlin.collections
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt:[118,80] Cannot infer a type for this parameter. Please specify                                                 it explicitly.
[ERROR] /root/RuneBot/RuneBot/src/main/kotlin/com/gmail/arhamjsiddiqui/runebot/e                                                ntity/Player.kt:[129,62] Unresolved reference: PlayersRecord
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit                                                ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea                                                d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc                                                eption`

I decided to start fresh (reinstalling), and I wound up getting this error.  What should I do?

**Comment by Arham4** [comment]
Now that I look back at this, this may have been because you need to change the credentials in pom.xml to be your database.
```
                    <jdbc>
                        <driver>org.postgresql.Driver</driver>
                        <url>jdbc:postgresql://ADDRESS:PORT(typically 5432)/DB_NAME</url>
                        <user>DB_USERNAME</user>
                        <password>DB_PASSWORD</password>
                    </jdbc>
```
Sorry, I just noticed this. It seems that that may be the problem, as it struggles to load jooq's classes which are generated by these credentials.

**Comment by Benroyz** [comment]
Hi, I changed those stuff. I ran into the issues:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.gmail.arhamjsiddiqui.runebot:RuneBot:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 100, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building RuneBot 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ RuneBot ---
[WARNING]
java.lang.ClassNotFoundException: com.gmail.arhamjsiddiqui.runebot.RuneBot
    at java.net.URLClassLoader.findClass (URLClassLoader.java:466)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:566)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:499)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:270)
    at java.lang.Thread.run (Thread.java:844)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.446 s
[INFO] Finished at: 2018-08-18T00:50:03-04:00
[INFO] Final Memory: 12M/60M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project RuneBot: An exception occured while executing the Java class. com.gmail.arhamjsiddiqui.runebot.RuneBot -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

What should I do?

**Comment by Arham4** [comment]
Are you sure you did `mvn clean install` before running? You don't have to do it every time, but at least the first time.

**Comment by Benroyz** [comment]
Yes, I did it for the first time. I just did it again by reinstalling RuneBot - I'm still having the issue.

**Comment by Arham4** [comment]
Man, now that one's got me stumped. You running this on Linux? Some Google results told me that may require some modifications. I'm not sure what modifications those are, though.

**Comment by Benroyz** [comment]
Yes, I am still running on Linux through the terminal.

**Comment by Arham4** [comment]
Yeah, definitely stumped. Especially because I have no way to test it.

**Comment by Arham4** [comment]
This project is now being rewritten in JavaScript.
